### ISSUE TITLE
Version 0.31 provides breaking changes 

### ISSUE THREAD

**Issue by reinfi** [OxCom/zf3-twig#14]
Hi,

are you aware of the problem that with 0.31 you're forced to use TwigModel to render Trees?

This breaks our whole application as we use ViewModel from Zend instead of the twig model.

https://github.com/OxCom/zf3-twig/compare/v0.2.1...master#diff-3a6b504b34e40a474f147f1ce59d6ccaR244

This should be mentioned somewhere. As a fix we will now extend your TwigRenderer with an own implementation of canRenderTrees.

Best regards
Martin

**Comment by OxCom** [comment]
Please, provide minimal reproducible example of your issue (configuration and example, with view and model, so I will be able to reproduce this)?

As quick solution: you can lock dependencies in composer at suitable version.
