### ISSUE TITLE
Laminas update

### ISSUE THREAD

**Issue by reinfi** [OxCom/zf3-twig#15]
Hey!

Would you like to update this library to Laminas or add a new package because of zf3 in its package name?

Best regards
Martin

**Comment by OxCom** [comment]
Hello! 
Yes, I will update dependencies list in few days.

**Comment by OxCom** [comment]
Please check release v1.0.0

**Comment by reinfi** [comment]
Thanks, but we will not continue to use this library as it is not compatible anymore with normal twig and zend handling.
