### ISSUE TITLE
TwigRenderer is being forced despite settings

### ISSUE THREAD

**Issue by panychek** [OxCom/zf3-twig#16]
Hi. 

I have the `'force_twig_strategy'` option disabled and my view model (that gets passed into the rendering strategies through a `ViewEvent` object) is an instance of `Laminas\View\Model\ViewModel` - but `TwigRenderer` still kicks in for some of the templates.

This happens due to the following piece of code:

https://github.com/OxCom/zf3-twig/blob/811529e00d828c18705580338a9dff0c650eb06d/src/View/TwigStrategy.php#L70-L80

If a Twig loader is able to load a .twig template by the same name (as my intended template) - it'll force this view model to be rendered with a `TwigRenderer`.

**Comment by OxCom** [comment]
this part of code has been rolled back ( removed )
