### ISSUE TITLE
Broken after install of the module

### ISSUE THREAD

**Issue by SylvanoTombo** [OxCom/zf3-twig#17]
I have this error
 Uncaught Laminas\Di\Exception\MissingPropertyException: Could not resolve value for parameter "serviceManager" of type Interop\Container\ContainerInterface in class ZendTwig\Extension\Extension (requested as ZendTwig\Extension\Extension) in /home/esokia/Labs/laminas/vendor/laminas/laminas-di/src/Resolver/DependencyResolver.php:329
 Uncaught Laminas\Di\Exception\MissingPropertyException: Could not resolve value for parameter "serviceManager" of type Interop\Container\ContainerInterface in class ZendTwig\Extension\Extension (requested as ZendTwig\Extension\Extension) in /home/esokia/Labs/laminas/vendor/laminas/laminas-di/src/Resolver/DependencyResolver.php:329

**Comment by OxCom** [comment]
@SylvanoTombo could you provide basic example. I'm not able to reproduce it with ```laminas/laminas-mvc: 3.1.1```

**Comment by SylvanoTombo** [comment]
It's a fresh new project and i installed zend-twig but getting the error ..May be, i can put the code in github ?

**Comment by SylvanoTombo** [comment]
Here is the link to the project https://github.com/SylvanoTombo/laminas
