### ISSUE TITLE
Extends does not work

### ISSUE THREAD

**Issue by HesyRa** [OxCom/zf3-twig#2]
Hi,
The problem occured:
if we use extends and {{content|raw}} in parent it renders the whole page instead of block content,
if we don't include content|raw it doesn't render block at all
Are we doing something wrong?

File: layout/layout.twig
```
{% block header %}{% endblock %}
<section class="container">
    <!-- Page content placeholder -->
    {% block content %}{% endblock %}
</section>
{% block footer %}{% endblock %}
```

File: application/index/index.twig
```
{% extends 'layout/layout.twig' %}
{% block header %}
test header
{% endblock %}

{% block content %}
test content
{% endblock %}
```

**Comment by OxCom** [comment]
In last release I have been added new option to the module: [force_standalone](https://github.com/OxCom/zf3-twig/blob/master/config/module.config.php)

Also in [this commit](https://github.com/OxCom/zf3-twig/commit/4d139cd419ce3fe40bf28cdd431cd1e86a6436b9) I added test for Your issue. So everything is fine.

As I understood correctly You should have this output:
```
test header
<section class="container">
    <!-- Page content placeholder -->
    test content
</section>
````

Sorry, If I misunderstood You. 
Thank You!

**Comment by HesyRa** [comment]
Sry, just updated to lates version and it works fine. sry.
