### ISSUE TITLE
Re-implement getHelperPluginManager in TwigRenderer ?

### ISSUE THREAD

**Issue by Ppito** [OxCom/zf3-twig#3]
Hello,

I'm working on a ZF3 module of sass compiler, and I need to call the method getHelperPluginManager that implemented in PhpRenderer, but this method has been rename on getZendHelpers in your TwigRenderer.

Actually, I need to test the type of renderer for call the good method, but it will be simplest not to do this. 

```php
    public function prepareStyle(ViewEvent $e) {
        /** @var \Zend\View\Renderer\PhpRenderer|\ZendTwig\Renderer\TwigRenderer $renderer */
        $renderer = $e->getRenderer();
        if ($renderer instanceof \ZendTwig\Renderer\TwigRenderer) {
            $pluginManager = $renderer->getZendHelpers();
        } else {
            $pluginManager = $renderer->getHelperPluginManager();
        }
        $containerHeadLink = $pluginManager->get('headLink')->getContainer();
        // ...
    }
```

So is it possible to re-implement this method in TwigRenderer ?

**Comment by OxCom** [comment]
That's good point. Updated in master/dev branches. Changes will be available in next release

**Comment by OxCom** [comment]
New changes are available in release [v0.1.1](https://github.com/OxCom/zf3-twig/tree/v0.1.1)

**Comment by Ppito** [comment]
thx a lot, I will test it soon ;)

**Comment by Ppito** [comment]
All work's fine :D 
thx for your great jobs ;)
