### ISSUE TITLE
broken after install

### ISSUE THREAD

**Issue by keanor** [OxCom/zf3-twig#4]
by default, module contains \Zend\Navigation\View\HelperConfig::class

need add zendframework/zend-navigation to composer.json or remove from default configuration, else: 

Uncaught Zend\View\Exception\RuntimeException: Unable to resolve provided configuration to valid instance of Zend\ServiceManager\ConfigInterface in /<cut>/vendor/oxcom/zend-twig/src/Service/TwigHelperPluginManagerFactory.php:56

**Comment by OxCom** [comment]
Fixed in [v0.1.2](https://github.com/OxCom/zf3-twig/releases/tag/v0.1.2)
