### ISSUE TITLE
Why not embed instanceOf as an extension built into ZendTwig

### ISSUE THREAD

**Issue by celtic34fr** [OxCom/zf3-twig#5]
Hi, 
I use Twig in my personal project GraphicObjectTemplating (ZF2/ZF3).
Giving access to TWIG under ZF2 / ZF3 is interesting, but having an adaptation of the basic templates would be more useful, as your extension instanceOf.
If this can help you, I would have both extensions and basic templates to offer you
- layout/layout, error/index, error/404, application/index/index (templates),
- intanceOf, typeOf (test extensions),
- getclass, gettype, arrayexception (for error/index template), checkBoolean, substr, strpos, instring (function extensions),
- contains (subchain is in string), update (update of table by key / value), unset (deletion occurance in array by key) (filter extension)

If you are interested, I can send you the ZF3 sources by email at your request, not all in my project on github (celti34fr / graphic-object-templating)

I found in the TWIG repository a tag refused by Fabien POTENCIER: switch/case that I adapted, I can also provide you.

Gilbert ARMENGAUD
celtic34fr
gilbert.armengaud@gmail.com
(Béziers - Hérault - Occitanie - France)

**Comment by OxCom** [comment]
Hello,

Good idea, I will think about that, I'll provide You my decision in a week.

Thank You!

**Comment by OxCom** [comment]
I decided that this extensions for Twig should be created as separate packages, because all extensions will require more dependencies, that is not applicable.

So, it should be done as separate project per extension.
