### ISSUE TITLE
I can't activate the debug mode

### ISSUE THREAD

**Issue by celtic34fr** [OxCom/zf3-twig#6]
Hi,

During my development, I often use the tag dump () to check the contents of my variables.
I tried to activate this mode via a configuration file, but I had no result
Here is my configuration fde file in config / autoload:

`Use Application \ Twig \ Extension \ TwigFilterExtension;
Use Application \ Twig \ Extension \ TwigFunctionExtension;
Use Application \ Twig \ Extension \ TwigTestExtension;
Use Application \ Twig \ Extension \ TwigTagExtension;
return  [
    'Zend_twig' => [
        'Force_standalone' => true,
        'Invoke_zend_helpers' => true,
        'Environment_options' => [
            'Cache' => false,
            'Debug' => true
        ],
        'Loader_chain' => [
            \ZendTwig\Loader\MapLoader::class,
            \ZendTwig\Loader\StackLoader::class,
        ],
        'Extensions' => [
            \ZendTwig\Extension\Extension::class,
            'Debug' => 'Twig_Extension_Debug',
            'LoadString' => 'Twig_Extension_StringLoader',
            'PersonalFilter' => TwigFilterExtension::class,
            'PersonalFunction' => TwigFunctionExtension::class,
            'PersonalTest' => TwigTestExtension::class,
            'PersonalNode' => TwigTagExtension::class,
        ],
        'Helpers' => [
            'Configs' => [
                \Zend\Navigation\View\HelperConfig::class,
            ],
        ],
    ],
];

Did I configure my application correctly?
Is there another way to code this activation?

Thank you in advance for your help.

Gilbert ARMENGAUD
Celtic34fr
Gilbert.armengaud@gmail.com
(Béziers - Herault - Occitania - France)

**Comment by OxCom** [comment]
Looks like You have invalid config. Should be something like this:
```
'zend_twig'       => [
    'environment' => [
        // ...
        'debug' => true,
        // ...
    ],
    'extensions'  => [
        // ...
        \Twig_Extension_Debug::class,
        // ...
    ],
],
```

I think that You have issue in config file, beacuse all array keys in arrays should be in lower case.
Please, find test for Your issue [here](https://github.com/OxCom/zf3-twig/blob/develop/tests/ZendTwig/Extension/DebugExtensionTest.php)

**Comment by celtic34fr** [comment]
Thank's for all, now i can use debug in my developpement
